# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
use_sim_time: true
moveit_simple_controller_manager:
  controller_names:
    - scara_controller
    - gripper_controller

  scara_controller:
    type: FollowJointTrajectory
    joints:
      - arm1_joint
      - arm2_joint
      - gripper_rod_joint
      - cylinder_joint
    action_ns: follow_joint_trajectory
    default: true
    use_sim_time: true
  gripper_controller:
    type: FollowJointTrajectory
    joints:
      - left_finger_joint
      - right_finger_joint
    action_ns: follow_joint_trajectory
    default: true
    use_sim_time: true